### ISSUE TITLE
Get stream URL

### ISSUE THREAD

**Issue by thundergreen** [shbatm/MMM-RTSPtoWeb#1]
Hello i tried to add this to my mirror . I read out the streams

![image](https://user-images.githubusercontent.com/13320319/174891168-14cbdaac-5a24-4c57-a679-ad61a1b1ba83.png)

but now i am stuck at the url Dunno how to build the url according to my screenshot

**Comment by thundergreen** [comment]
I tried this url 👍 http://192.168.1.41:8083/stream/camera.doorbell_webrtc/channel/0/webrtc but page not found issue here :(

**Comment by thundergreen** [comment]
![image](https://user-images.githubusercontent.com/13320319/174893130-fa001f02-7dca-4b3f-acca-a900d578c002.png)


this does not work :( 

curl http://127.0.0.1:8083/stream/{STREAM_ID}/channel/{CHANNEL_ID}/hlsll/live/index.m3u8 this works and it is downloading the m3u file.

**Comment by shbatm** [comment]
> I tried this url 👍 http://192.168.1.41:8083/stream/camera.doorbell_webrtc/channel/0/webrtc but page not found issue here :(

This looks like the URL you should be using. Are you getting the page not found error when using that in the mirror or just trying to browse there on your browser?

You can also enable debug logging in the RTSPtoWeb - WebRTC Add-On and see if you get any additional information.

**Comment by thundergreen** [comment]
I get this in both. mirror and browser. Debug is on I only get:

```
time="2022-06-22T19:03:27+02:00" level=error msg="Stream error restart stream stream stop rtsp signal" call=Restart
time="2022-06-22T19:03:29+02:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.garden_upstairs_webrtc
time="2022-06-22T19:03:29+02:00" level=info msg="Success connection RTSP" call=Start channel=0 func=StreamServerRunStream module=core stream=camera.garden_upstairs_webrtc
time="2022-06-22T19:09:08+02:00" level=error msg="Stream error restart stream stream stop rtsp signal" call=Restart
time="2022-06-22T19:09:10+02:00" level=info msg="Run stream" call=Run channel=0 func=StreamServerRunStreamDo module=core stream=camera.garden_upstairs_webrtc
time="2022-06-22T19:09:10+02:00" level=info msg="Success connection RTSP" call=Start channel=0 func=StreamServerRunStream module=core stream=camera.garden_upstairs_webrtc
```

**Comment by thundergreen** [comment]
![image](https://user-images.githubusercontent.com/13320319/175099968-9d8d8379-71ef-47c6-965b-c1c5915a023e.png)

**Comment by thundergreen** [comment]
I also tried adding this URL:

http://192.168.1.41:8083/pages/player/webrtc/camera.doorbell_webrtc/0

which is shown in the web interface but without success

![image](https://user-images.githubusercontent.com/13320319/175100413-7cf49bc0-9691-43d4-a55f-2ef85bc5a60a.png)

**Comment by thundergreen** [comment]
Oo just tried again.. it works :)

**Comment by lawrence-jeff** [comment]
@thundergreen  - Can you clarify which stream URL you finally got to work please? Having the same issue
