### ISSUE TITLE
Installation commands

### ISSUE THREAD

**Issue by papinist** [shbatm/MMM-RTSPtoWeb#12]
I know I can result a noob, but.. what are the installation commands?
I am not sure if all modules have the same installation procedure so to be sure I'm asking here.
Thanks!

**Comment by lawrence-jeff** [comment]
Same as any other module

cd ~/MagicMirror/modules
git clone https://github.com/shbatm/MMM-RTSPtoWeb
cd MMM-RTSPtoWeb
npm install
