### ISSUE TITLE
Add option for couple cameras

### ISSUE THREAD

**Issue by hillaliy** [shbatm/MMM-RTSPtoWeb#7]
I can you add support to add more then one camera on one module?  A grid?

**Comment by Imnotme1009** [comment]
If you want more than one stream playing at once, put something like this in the config:

 {
      module: "MMM-RTSPtoWeb",
      position: "top_right",
      header: "Stream 1",
      config: {
        width: "100%",
        url: "http://127.0.0.1:8083/stream/XXX/channel/0/webrtc"
      }
 },
 {
      module: "MMM-RTSPtoWeb",
      position: "bottom_right",
      header: "Stream 2",
      config: {
        width: "100%",
        url: "http://127.0.0.1:8083/stream/XXX/channel/0/webrtc"
      }
 },
